ErasmusBlogWrb/Controllers/ContentController.cs
using DataAccessLayer.Abstract;
using DataAccessLayer.Implementation;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ErasmusBlogWrb.Controllers
{
    public class ContentController : Controller
    {
        public IContentHeader contentservice;
        public UserManager<ApplicationUser> usermanager;
        public IWriterService writerservice;
        public IHeaderService headerService;
        public ContentController(IContentHeader contentservicem, UserManager<ApplicationUser> UserManager, IWriterService writerservice, IHeaderService headerservice)
        {
            this.contentservice = contentservicem;
            this.usermanager = UserManager;
            this.writerservice = writerservice;
            this.headerService = headerservice;
        }

        public IActionResult Index()
        {
            var d = contentservice.GetAll();
            return View(d);
        }
        [HttpGet]
        public ActionResult Add(int Id)
        {
            ViewBag.d = Id;
            return View();
        }
        [HttpPost]
        public ActionResult Add(Content model)
        {
            
            model.ContentDate = DateTime.Now.ToShortDateString();
            var appUserNick  = usermanager.FindByIdAsync(usermanager.GetUserId(User)).Result.UserName;
            var user = writerservice.GetByUsername(appUserNick);
            model.WriterId = user.WriterId;

            contentservice.Add(model);
            return RedirectToAction(nameof(Index));

        }
        public ActionResult Update(int id)
        {
            var model = contentservice.GetById(id);
            return View(model);
        }
        public ActionResult Update(Content model)
        {
            contentservice.Update(model);
            return RedirectToAction(nameof(Index));
        }
        public ActionResult Delete(int id)
        {
            var model = contentservice.GetById(id);
            contentservice.Delete(model);
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public ActionResult GetContentById(int id)
        {
            var model = contentservice.GetContentById(id);
            return View(model);
        }
    }
}

ErasmusBlogWrb/Views/Content/Add.cshtml
@model EntityLayer.Concrete.Content

@{

    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/css2/bootstrap.min.css" rel="stylesheet" />

<br />
@using (Html.BeginForm("Add", "Content", FormMethod.Post))
{
    <input type="hidden" name="HeaderId"  value="@ViewBag.d" />
    <br />
    <div class="form-group">
        @Html.Label("Content Value")
        @Html.TextBoxFor(x=>x.ContentValue)
    </div>


    <button>Save</button>


}

ErasmusBlogWrb/Views/Content/GetContentById.cshtml
@model List<EntityLayer.Concrete.Content>


@{
    ViewBag.Title = "ContentByHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    @foreach (var item in Model)
    {
        
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">

                <!-- Timelime example  -->
                <div class="row">
                    <div class="col-md-12">
                        <!-- The time line -->
                        <div class="timeline">
                            <!-- timeline time label -->
                            <div class="time-label">
                                <span class="bg-success">@item.ContentDate</span>
                            </div>
                            <!-- /.timeline-label -->
                            <!-- timeline item -->
                            <div>
                                <i class="fas fa-comment bg-yellow"></i>
                                <div class="timeline-item">
                                    <h3 class="timeline-header"><a href="#">@item.Writer.WriterName</a> @item.Header.HeaderName</h3>
                                    <div class="timeline-body">
                                        @item.ContentValue
                                    </div>
                                </div>
                            </div>
                            <!-- END timeline item -->
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->}
</body>
</html>

ErasmusBlogWrb/Views/Content/Index.cshtml
@model List<EntityLayer.Concrete.Content>
@{

    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<link href="~/css2/bootstrap.min.css" rel="stylesheet" />

<br />
<table class="table table-bordered">
    <tr>
        <th>Value</th>
        <th>Header Name</th>
        <th>Writer Name</th>
        <th>Date</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>@item.ContentValue</td>
            <td>@item.Header.HeaderName</td>
            <td>@item.Writer.WriterName</td>
            <td>@item.ContentDate</td>
            <td><a href="/Content/Delete/@item.ContentId" class="btn btn-light">Delete</a></td>
            <td><a href="/Content/Update/@item.ContentId" class="btn btn-outline-secondary">Update</a></td>
        </tr>

    }
</table>