ErasmusBlogWrb/Controllers/MessageController.cs
using DataAccessLayer.Abstract;
using EntityLayer.Concrete;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ErasmusBlogWrb.Controllers
{
    public class MessageController : Controller
    {
        public IMessageService messageservice;
        public IWriterService writerservice;
        public UserManager<ApplicationUser> usermanager;

        public MessageController(IMessageService messageservice, IWriterService writerservice, UserManager<ApplicationUser> Usermanager)
        {
            this.messageservice = messageservice;
            this.writerservice = writerservice;
            this.usermanager= Usermanager;
        }

        public IActionResult Index(int id)
        {
            messageservice.GetByUserId(id);
            return View();
        }
        [HttpGet]
        public ActionResult Add(int id)
        {
            var t = writerservice.GetById(id);
            ViewBag.b = t.WriterMail;
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> Add(Message model)
        {
            model.MessageDate = DateTime.Now.ToShortDateString();

            var t = usermanager.FindByIdAsync(usermanager.GetUserId(User));
            model.SenderMail= t.Result.Email;

            messageservice.Add(model);
            return RedirectToAction(nameof(Index));
        }
        public ActionResult GetListById(int id)
        {
            messageservice.GetByUserId(id);
            return View(messageservice.GetByUserId(id));
        }
        public ActionResult GetList()
        {
            var t = usermanager.FindByIdAsync(usermanager.GetUserId(User));
            return View(messageservice.GetAll().Where(p=>p.SenderMail == t.Result.Email).ToList());
        }
    }
}

ErasmusBlogWrb/Views/Message/Add.cshtml
@model EntityLayer.Concrete.Message
@{
    ViewBag.Title = "NewMessage";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 3 | Compose Message</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <!-- Theme style -->
    <!-- summernote -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.css">

    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote.min.js"></script>
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

</head>
<body class="hold-transition sidebar-mini">
    
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Compose</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Compose</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-3">
                    <a href="mailbox.html" class="btn btn-primary btn-block mb-3">Back to Inbox</a>
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Folders</h3>
                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                    <i class="fas fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <div class="card-body p-0">
                            <ul class="nav nav-pills flex-column">
                                <li class="nav-item active">
                                    <a href="/Message/Index/" class="nav-link">
                                        <i class="fas fa-inbox"></i> Inbox
                                        <span class="badge bg-primary float-right">12</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="far fa-envelope"></i> Sent
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a href="#" class="nav-link">
                                        <i class="far fa-trash-alt"></i> Trash
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                    <div class="card">
                        <div class="card-header">
                            <h3 class="card-title">Labels</h3>
                            <div class="card-tools">
                                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                    <i class="fas fa-minus"></i>
                                </button>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <ul class="nav nav-pills flex-column">
                                <li class="nav-item">
                                    <a class="nav-link" href="#"><i class="far fa-circle text-danger"></i> Important</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#"><i class="far fa-circle text-warning"></i> Promotions</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="#"><i class="far fa-circle text-primary"></i> Social</a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.card-body -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
                <div class="col-md-9">
                    <div class="card card-primary card-outline">
                        <div class="card-header">
                            <h3 class="card-title">Compose New Message</h3>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body">

                            @using (Html.BeginForm("Add", "Message", FormMethod.Post))
                            {
                                <input type="hidden" name="ReceiverMail" value="@ViewBag.b" />
                                
                                <br />
                                <div class="form-group"> 
                                    @Html.Label("Message Subject")
                                    @Html.TextBoxFor(x=>x.MessageSubject)
                                </div>
                                <div class="form-group">
                                    @Html.Label("Message Value")
                                    @Html.TextAreaFor(x=>x.MessageContent)
                                </div>


                                <button>Save</button>


                            }
                           
                        </div>
                        <!-- /.card-body -->
                  
                        <!-- /.card-footer -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <!-- /.content-wrapper -->
    <!-- Control Sidebar -->
    <!-- /.control-sidebar -->
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
    <!-- Summernote -->
    <script src="~/AdminLTE-3.0.4/plugins/summernote/summernote-bs4.min.js"></script>
    <!-- Page Script -->
    <script>
        $(function () {
            //Add text editor
            $('#compose-textarea').summernote()
        })</script>
</body>
</html>

ErasmusBlogWrb/Views/Message/GetList.cshtml
@model List<EntityLayer.Concrete.Message>
@{

    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<link href="~/css2/bootstrap.min.css" rel="stylesheet" />

<br />
<table class="table table-bordered">
    <tr>
        <th>Message Subject</th>
        <th>Message Content</th>
        <th>Message Date</th>
        <th>Sender</th>
    </tr>

    @foreach (var item in Model)
    {
            <tr>
                <td>@item.MessageSubject</td>
                <td>@item.MessageContent</td>
                <td>@item.MessageDate</td>
                <td>@item.SenderMail</td>
                <td><a href="/Content/Delete/@item.MessageId" class="btn btn-light">Delete</a></td>
                <td><a href="/Content/Update/@item.MessageId" class="btn btn-outline-secondary">Update</a></td>
            </tr>

    }
</table>