ErasmusBlogWrb/Controllers/WriterController.cs
using Castle.Core.Resource;
using DataAccessLayer.Abstract;
using DataAccessLayer.Implementation;
using EntityLayer.Concrete;
using EntityLayer.DTO;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics.Metrics;

namespace ErasmusBlogWrb.Controllers
{
    public class WriterController : Controller
    {
        public IWriterService writeser;
        public UserManager<ApplicationUser> usermanager;
        public WriterController(IWriterService writeser, UserManager<ApplicationUser> userManager)
        {
            this.writeser = writeser;
            this.usermanager = userManager;
        }

        public IActionResult Index()
        {
            var list = writeser.GetAll();
            return View(list);
        }
        [HttpGet]
        public ActionResult Add()
        {
            return View();

        }
        [HttpPost]
        public ActionResult Add(Writer model)
        {

            //var id = usermanager.GetUserId(User);
            //var tt = new WritersAndUsersRelationship
            //{
            //    UserId = id,
            //    WritersId = model.WriterId
            //};

            ModelState.Remove("Contents");
            ModelState.Remove("Headers");
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            else
            {
                var result = writeser.Add(model);
                if (result)
                {
                    RegistrationModel data = new RegistrationModel
                    {
                        Email = model.WriterMail,
                        Name = model.WriterName,
                        Username = model.WriterUsername,
                        Password = model.WritePassword,
                        PasswordConfirm = model.WritePassword,
                        WritersId= model.WriterId,
                        
                    };

                    //TempData["msg"] = "Added Successfully";
                    return RedirectToAction("RegisterSeri", "UserAuthentication", data);

                }
                else
                {
                    TempData["msg"] = "Error on server side";
                    return View(model);
                }
            }
        }
        [HttpGet]
        public ActionResult Update(int id)
        {
            var model = writeser.GetById(id);
            return View(model);
        }
        [HttpPost]
        public ActionResult Update(Writer model)
        {
            var result = writeser.Update(model);
            if (result)
            {
                TempData["msg"] = "Updated Successfully";
                return RedirectToAction(nameof(GetList));
            }
            else
            {
                TempData["msg"] = "Error on server side";
                return View(model);
            }

        }
        public ActionResult GetList()
        {
            var list = writeser.GetAll();
            return View(list);
        }
        public ActionResult WriterProfile(int id)
        {
            
            return View(writeser.GetById(id));
        }
        public ActionResult Delete(int id)
        {

            writeser.Delete(writeser.GetById(id));
            return RedirectToAction(nameof(Index));
        }
    }
}

ErasmusBlogWrb/Views/Writer/Add.cshtml
@model EntityLayer.Concrete.Writer

@{
 
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/css2/bootstrap.min.css" rel="stylesheet" />

<br />
@using (Html.BeginForm("Add", "Writer", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Writer Password")
        @Html.TextBoxFor(x=>x.WritePassword)
    </div>
    <div class="form-group">
        @Html.Label("Writer Name")
        @Html.TextBoxFor(x=>x.WriterName)
    </div>
    <div class="form-group">
        @Html.Label("Writer Surname")
        @Html.TextBoxFor(x=>x.WriterSurname)
    </div>
    <div class="form-group">
        @Html.Label("Writer Image")
        @Html.TextBoxFor(x=>x.WriterImage)
    </div>
    <div class="form-group">
        @Html.Label("Writer Mail")
        @Html.TextBoxFor(x=>x.WriterMail)
    </div>
    <div class="form-group">
        @Html.Label("Writer Surname")
        @Html.TextBoxFor(x=>x.WriterUsername)
    </div>

    <button>Save</button>


}

ErasmusBlogWrb/Views/Writer/Index.cshtml
@model List<EntityLayer.Concrete.Writer>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- /.navbar -->
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Writer Page</h1>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Default box -->
        <div class="card card-solid">
            <div class="card-body pb-0">
                <div class="row d-flex align-items-stretch">
                    @foreach (var item in Model)
                    {
                        <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                            <div class="card bg-light">
                                <div class="card-header text-muted border-bottom-0">
                                    User
                                </div>
                                <div class="card-body pt-0">
                                    <div class="row">
                                        <div class="col-7">
                                            <h2 class="lead"><b>@item.WriterName </b> <b>@item.WriterSurname</b></h2>
                                            <p class="text-muted text-sm"><b>About: </b> </p>
                                            <ul class="ml-4 mb-0 fa-ul text-muted">
                                                <li class="small"><span class="fa-li"><i class="fas fa-lg fa-building"></i></span> Email: @item.WriterMail</li>
                                                <li class="small"><span class="fa-li"><i class="fas fa-lg fa-phone"></i></span> Phone #: + 800 - 12 12 23 52</li>
                                            </ul>
                                        </div>
                                        <div class="col-5 text-center">
                                            <img src="@item.WriterImage" alt="" class="img-circle img-fluid">
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <div class="text-right">
                                        <a href="/Writer/Delete/@item.WriterId" class="btn btn-sm bg-teal">
                                            <i class="fas fa-delicious"></i>Delete Profile
                                        </a>
                                        <a href="/Writer/Update/@item.WriterId" class="btn btn-sm btn-primary">
                                            <i class="fas fa-user"></i> Edit Profile
                                        </a>
                                        <a href="/Message/Add/@item.WriterId">
                                            <i class="fas fa-user"></i> Send Message
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
        <!-- /.card -->
    </section>
    <!-- /.content -->
    <a href="/Writer/Add" class="btn btn-danger">Add Writer</a>
</body>
</html>

ErasmusBlogWrb/Views/Writer/Update.cshtml
@model EntityLayer.Concrete.Writer

@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/css2/bootstrap.min.css" rel="stylesheet" />

<br />
@using (Html.BeginForm("Update", "Writer", FormMethod.Post))
{
    <div hidden class="form-group">
        @Html.Label("Writer Id")
        @Html.TextBoxFor(x=>x.WriterId)
    </div>
    <div hidden class="form-group">
        @Html.Label("Writer Password")
        @Html.TextBoxFor(x=>x.WritePassword)
    </div>

    <div class="form-group">
        @Html.Label("Writer Mail")
        @Html.TextBoxFor(x=>x.WriterMail)
    </div>
    <div class="form-group">
        @Html.Label("Writer Image")
        @Html.TextBoxFor(x=>x.WriterImage)
    </div>
    <div class="form-group">
        @Html.Label("Writer Name")
        @Html.TextBoxFor(x=>x.WriterName)
    </div>

    <div class="form-group">
        @Html.Label("Writer Surname")
        @Html.TextBoxFor(x=>x.WriterSurname)
    </div>
    <button>Save</button>
}

ErasmusBlogWrb/Views/Writer/WriterProfile.cshtml
@model EntityLayer.Concrete.Writer

@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<link href="~/css2/bootstrap.min.css" rel="stylesheet" />

<br />
<table class="table table-bordered">
    <tr>
        <th>Name</th>
        <th>Surname</th>
        <th>Mail</th>
        <th>Username</th>
        <th>Image</th>
        
    </tr>
    <tr>
        <th>@Model.WriterName</th>
        <th>@Model.WriterSurname</th>
        <th>@Model.WriterMail</th>
        <th>@Model.WriterUsername</th>
        <th>@Model.WriterImage</th>
    </tr>
</table>

<a href="/Category/GetList" class="btn btn-outline-secondary">Category List</a>
<a href="/Category/Add" class="btn btn-outline-success">New Category</a>